# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f8f2fcdc999a514e620e8799d411b0c0a6ae84474545d5470d5ec61da7ce1b745baf2a84a6711c9ea4350482bb7d8346851f109322bec6bcd782bea566529d

test:
  secret_key_base: a40d52560ff4e39e2855b2816c1512357300a0406d620c7def3c61ae61398db08af946210dee5704159583fc355372a47bc94c1d780c6f6f1d9a1eabe4384ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
